# Start with CUDA base image
FROM nvidia/cuda:11.6.1-cudnn8-runtime-ubuntu20.04
LABEL maintainer="Ummar Abbas <uabbas@hbku.edu.qa>"

# Install Miniconda
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 

# Create conda environment
# COPY ./ehr_deidentification /ehr_deidentification
RUN git clone git@github.com:qcrisw/ehr_deidentification.git
WORKDIR /ehr_deidentification

RUN conda env create -f /ehr_deidentification/deid.yml
RUN echo "source activate deid" > ~/.bashrc
ENV PATH /opt/conda/envs/deid/bin:$PATH
RUN /root/miniconda3/envs/deid/bin/python -m pip install robust-deid
RUN apt update && apt install -y jq && apt install -y moreutils && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]